org: '1302216408'
app: img-bed
stage: dev
component: koa
name: img-bed
inputs:
  entryFile: app.js #以您实际入口文件名为准
  src:
    src: ./
    exclude:
      - .env
      # - node_modules/**
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - https
    environment: release
    serviceTimeout: 60
    customDomains:
      - domain: upload.niuhk.cn
        certificateId: rkJyqyPL
        isDefaultMapping: false
        pathMappingSet:
          - path: /
            environment: release
        protocols:
          - https
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: false
    timeout: 30
    memorySize: 128
  # layers:
  #   - name: '${output:${stage}:${app}:test-layer.name}'
  #     version: '${output:${stage}:${app}:test-layer.version}'
